# Generated by Django 6.0.4 on 2026-04-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teaches_classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='users.classinfo'),
        ),
    ]
