# Generated by Django 6.0.4 on 2026-04-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_teaches_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teaches_classes',
        ),
    ]
