# Generated by Django 6.0.4 on 2026-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("choice", "选择题"),
                            ("fill", "填空/解答题"),
                            ("judge", "判断题"),
                            ("draw", "画图题"),
                        ],
                        max_length=20,
                        verbose_name="题型",
                    ),
                ),
                ("stem", models.TextField(verbose_name="题干(支持富文本)")),
                (
                    "options",
                    models.JSONField(blank=True, null=True, verbose_name="选项(JSON)"),
                ),
                ("answer", models.JSONField(verbose_name="标准答案与规则(JSON)")),
                ("analysis", models.TextField(blank=True, verbose_name="解析")),
                (
                    "difficulty",
                    models.IntegerField(default=1, verbose_name="难度(1-5)"),
                ),
                (
                    "knowledge_points",
                    models.JSONField(
                        blank=True, null=True, verbose_name="知识点集合(JSON)"
                    ),
                ),
            ],
            options={
                "verbose_name": "试题",
                "verbose_name_plural": "试题",
            },
        ),
    ]
