# Generated by Django 6.0.4 on 2026-04-09 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="交卷时间"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="总用时(秒)"
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(blank=True, null=True, verbose_name="正确率"),
                ),
            ],
            options={
                "verbose_name": "练习场次",
                "verbose_name_plural": "练习场次",
            },
        ),
        migrations.CreateModel(
            name="QuestionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.JSONField(verbose_name="学生提交的答案")),
                ("is_correct", models.BooleanField(verbose_name="是否正确")),
                (
                    "time_spent",
                    models.IntegerField(default=0, verbose_name="该题用时(秒)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ErrorBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consecutive_correct",
                    models.IntegerField(default=0, verbose_name="连续答对次数"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否仍在错题本中"),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="首次做错时间"
                    ),
                ),
                (
                    "last_practiced",
                    models.DateTimeField(
                        auto_now=True, verbose_name="最后一次练习时间"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
            ],
        ),
    ]
