# Generated by Django 6.0.4 on 2026-04-15 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0002_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorbook',
            options={'verbose_name': '错题本', 'verbose_name_plural': '错题本'},
        ),
        migrations.AddIndex(
            model_name='errorbook',
            index=models.Index(fields=['student', 'is_active'], name='practices_e_student_b29457_idx'),
        ),
    ]
